name: Run Discord Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install discord.py python-dotenv
      - name: Ejecutar bot 1
     run: python bot.py
    env:
     DISCORD_TOKEN_1: ${{ secrets.DISCORD_TOKEN_1 }}
   - name: Ejecutar bot 2
   run: python Bott.py
   env:
  DISCORD_TOKEN_2: ${{ secrets.DISCORD_TOKEN_2 }}
