name: Run Discord Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install discord.py python-dotenv

    - name: Ejecutar bots
      run: |
        python bot.py &
        python Bott.py &
        wait
      env:
        DISCORD_TOKEN_1: ${{ secrets.DISCORD_TOKEN_1 }}
        DISCORD_TOKEN_2: ${{ secrets.DISCORD_TOKEN_2 }}
